spring.application.name=myaccountsservice
server.port=3000



spring.profiles.active=dev

# A profile example
#spring.datasource.url=${URL_BASE}
#spring.datasource.username=${USERNAME}
#spring.datasource.password=${PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#jwt.accesstoken.key=${JWT_ASSES}
#jwt.logintoken.key=${JWT_LOGIN}